### ISSUE TITLE
Todos os componentes devem estar no repositório

### ISSUE THREAD

**Issue by fabianomoreira** [Matheusvgdr/minhaCarteiraApp#2]
Não encontrei o Lucas como colaborador. Ele não está com acesso ao projeto?

**Comment by Matheusvgdr** [comment]
O convite foi enviado, só estamos esperando ele aceitar.

**Comment by fabianomoreira** [comment]
Alguém no projeto precisa assumir o papel de Scrum Master, e nesse caso, fazer as "cobranças" necessárias para o bom andamento do projeto.

**Comment by Matheusvgdr** [comment]
Entendido, todos os integrantes estão no repositório.
